apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-bird-service
spec:
  clusterIP: {{ .Values.bird.clusterIP }}
  selector:
    app: {{ .Release.Name }}-bird
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.bird.containerPort }}
      nodePort: {{ .Values.bird.nodePort }}  # Set this to the desired node port
  type: NodePort

